version: '3'
#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.     #
#---------------------------------------------------------------------#
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /data/docker/homarr/configs:/app/data/configs
      - /data/docker/homarr/icons:/app/public/icons
      - /data/docker/homarr/data:/data
    ports:
      - '7575:7575'
   
networks:
  default:
    external: true
    name: swag
