version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /data/docker/npm/data:/data
      - /data/docker/npm/letsencrypt:/etc/letsencrypt

networks:
  default:
    external: true
    name: swag
