version: "3.2"
services:
  redbot:
    container_name: redbot
    image: phasecorex/red-discordbot:full
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
    volumes:
      - /data/docker/redbot:/data
    environment:
      - TOKEN=[YOUR DISCORD TOKEN]
      - PREFIX=.
      - TZ=[YOUR TIMEZONE]
      - PUID=1000
      - NICENESS=10

networks:
  default:
    external: true
    name: swag
